{
 "title": "UPS",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "apcupsd_battery_charge_percent{job=\"ups\"}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "apcupsd_ups_load_percent{job=\"ups\"}"
    }
   ]
  },
  {
   "title": "Time Left",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds{job=\"ups\"}"
    }
   ]
  },
  {
   "title": "Cumulative Time on Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "apcupsd_battery_cumulative_time_on_seconds_total{job=\"ups\"}"
    }
   ]
  }
 ]
}